---
# See https://pre-commit.com/ for usage and config
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-install
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
  - repo: local
    hooks:
      - id: ruff_check
        name: Ruff Check
        stages: [commit]
        language: system
        entry: poetry run ruff check
        types: [python]
        args: [--fix]
        require_serial: false
      - id: ruff_format
        name: Ruff Format
        stages: [commit]
        language: system
        entry: poetry run ruff format
        types: [python]
        require_serial: false
      - id: pytest
        name: pytest
        stages: [push]
        language: system
        entry: poetry run pytest
        types: [python]
        pass_filenames: false

